### ISSUE TITLE
When you extract it to .aar file TextRecognizerOptions is missing on the dependancies.

### ISSUE THREAD

**Issue by jshahriyarbadalov** [idpass/smartscanner-core#126]
## Steps to Reproduce the Problem

E/AndroidRuntime: FATAL EXCEPTION: pool-22-thread-1
    Process: az.dpc.sima, PID: 4480
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/text/latin/TextRecognizerOptions;
        at org.idpass.smartscanner.lib.mrz.MRZAnalyzer.analyze(MRZAnalyzer.kt:90)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:481)
        at androidx.camera.core.-$$Lambda$ImageAnalysis$nIAz9HE3CRS1_vFJkazzoVeZNbw.analyze(Unknown Source:2)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:285)
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$G911WPAXBTMbNyPtAa3t9bV5EPI.run(Unknown Source:14)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.text.latin.TextRecognizerOptions" on path: DexPathList[[zip file "/data/app/~~id3Rr22dgRzp50BAykMZUg==/az.dpc.sima-lXBH21zszVyC2tlClCCeWg==/base.apk"],nativeLibraryDirectories=[/data/app/~~id3Rr22dgRzp50BAykMZUg==/az.dpc.sima-lXBH21zszVyC2tlClCCeWg==/lib/arm64, /data/app/~~id3Rr22dgRzp50BAykMZUg==/az.dpc.sima-lXBH21zszVyC2tlClCCeWg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.idpass.smartscanner.lib.mrz.MRZAnalyzer.analyze(MRZAnalyzer.kt:90) 
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:481) 
        at androidx.camera.core.-$$Lambda$ImageAnalysis$nIAz9HE3CRS1_vFJkazzoVeZNbw.analyze(Unknown Source:2) 
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:285) 
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$G911WPAXBTMbNyPtAa3t9bV5EPI.run(Unknown Source:14)

## Context

- Version:

**Comment by rjmangubat23** [comment]
@jshahriyarbadalov please make sure to add mlkit to your `build.gradle` dependencies as well. 

`implementation 'com.google.mlkit:text-recognition:16.0.0-beta6'`

**Comment by jshahriyarbadalov** [comment]
Thank you, it worked 😊
