### ISSUE TITLE
MRZ reading in portrait crash

### ISSUE THREAD

**Issue by gsipic** [idpass/smartscanner-core#152]
## Current Behaviour

The app will crash when trying to read MRZ in portrait position

```
java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
                   at android.graphics.Bitmap.createBitmap(Bitmap.java:916)
                   at android.graphics.Bitmap.createBitmap(Bitmap.java:873)
                   at org.idpass.smartscanner.lib.mrz.MRZAnalyzer.analyze(MRZAnalyzer.kt:100)
```

## Expected Behaviour

It should not crash and scanning MRZ with Portrait orientation should work

## Steps to Reproduce the Problem

1. Open SmartScanner App
2. Go back to the home page and try to open MRZ, it will crash automatically

## Context
- Version: 0.4.6

**Comment by jlduragos** [comment]
Hello, 

Can you please provide us the following details:
1.  Model of the device used
2. Android OS version

**Comment by gsipic** [comment]
Model : Samsung A20e
Android Version 11
